### PR TITLE
Add DBTYPE variable

### PR DESCRIPTION
**Pull request by cbrunnkvist**
Setting it...sets the desired database type. And both (config|parameters).yml is updated correctly out of the box now. :sunflower:

### CODE REVIEW

**Comment by allan-simon** [comment]
can you update the README to reflect this new possibility

**Comment by cbrunnkvist** [comment]
One more thing: handling non-existent parameters.yml

Once you checkout on a new workstation, the provisioning step needs to create the parameters.yml from parameters.yml.dist, just like the installer does for you. Otherwise, the consecutive update params step will fail ...

**Comment by cbrunnkvist** [comment]
Yay my apprentices discovered one more: NOTHING works because the cache bootstrap file is not under version control. It _is_ generated in the `post-install-cmd` step of composer, but there might be some situations where things happen out of order and...confusion sets in.

**Comment by cbrunnkvist** [comment]
(-last comment not directly related to this branch. Will fix elsewhere.)

**Comment by allan-simon** [comment]
looks great now , merged

**Pull request merged**
